name: Erlang-Legacy CI ğŸ®

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: Erlang-Legacy

jobs:

  checkLicense:
    name: Check Unity license âœ”ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ğŸ’€
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1 

  buildWebGL:
    needs: checkLicense
    name: Build for WebGL ğŸ–¥ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ‘ï¸â€ğŸ—¨ï¸
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache dependencies ğŸ”„ï¸
        uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ hashFiles('${{ env.PROJECT_PATH }}/Assets/**', '${{ env.PROJECT_PATH }}/Packages/**', '${{ env.PROJECT_PATH }}/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project ğŸ”§
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ env.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ env.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ env.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          targetPlatform: WebGL

      # Output
      - name: Upload artificat â¬†ï¸
        uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL

  deployPages:
    needs: buildWebGL
    name: Deploy to Github Pages ğŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ‘ï¸â€ğŸ—¨ï¸
        uses: actions/checkout@v2

      - name: Download artificat â¬‡ï¸
        uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/WebGL